### PR TITLE
Update steam_description_es.txt

### PR DESCRIPTION
**Pull request by ghost**
Just did some corrections and tweaks for the Spanish Steam description. I'm waiting for the updated in-game text to check those again in the next pull request (edit: or commits).

### CODE REVIEW

**Comment by ghost** [comment]
ah yeah, I forgot to say that I'll actually wait for the new text. And since I accidentally created another branch, this was gonna be closed whatsoever

**Comment by forthfora** [comment]
hiya, just pushed the new text, i've run the translation script in a special 'no translate' mode exclusively for the Spanish strings.txt

basically this means that all the text that already had translations should be preserved, and the new lines should have the value 'NO_TRANSLATION', hopefully it makes it easier for you

feel free to translate the new stuff now, and please let me know if you notice anything that didnt get preserved (which would mean that the code didnt work right)


also, there is one new pearl dialogue file, Heart_Pearlpup, it's using google translated text for now, feel free to translate it too if you have the time

**Comment by forthfora** [comment]
oh, and i figured out how to get symlinks to work with GitHub, so there is only one text folder now

**Comment by ghost** [comment]
cool, thanks! I might take a while since I'm also kind of fixing the older translations as well (hopefully until tomorrow)

**Pull request closed without merging**
