### PR TITLE
update text_chi

### PR DESCRIPTION
**Pull request by Linnnnnna**

### CODE REVIEW

**Comment by forthfora** [comment]
did you just improve the entire chinese translation?? thank you! I will proof read it somehow and have it in the next update, hopefully

你刚刚改进了整个中文翻译吗？谢谢你！我会以某种方式校对它并在下一次更新中包含它，希望

**Comment by Linnnnnna** [comment]
> did you just improve the entire chinese translation?? thank you! I will proof read it somehow and have it in the next update, hopefully
> 
> 你刚刚改进了整个中文翻译吗？谢谢你！我会以某种方式校对它并在下一次更新中包含它，希望

except 38-pearlcatpebbles.txt and 40-pearlcatpebbles.txt ( or something else，maybe later

**Comment by Linnnnnna** [comment]
0Y%Z4CK2VJ%LBSPKXJGQP{9

**Comment by forthfora** [comment]
Sorry this update is taking so long, there is a lot to do, but it should be nearly done now

Some new dialogue has been added + some old stuff has been tweaked

**Comment by Linnnnnna** [comment]
> Sorry this update is taking so long, there is a lot to do, but it should be nearly done now
> 
> Some new dialogue has been added + some old stuff has been tweaked

cc

**Pull request merged**
